### ISSUE TITLE
运行server报错

### ISSUE THREAD

**Issue by llfididi** [taozhi1010/nest-admin#2]
![image](https://github.com/taozhi1010/nest-admin/assets/51221182/cc94ae86-a1f0-4ae3-a874-3f6bd398908d)

**Comment by zyyGG** [comment]
在server/src/config/dev.yml中配置数据库和redis

**Comment by llfididi** [comment]
> 你的本地mysql和redis服务启动了吗？

没有😁

**Comment by zhengwenhong123** [comment]
> 你的本地mysql和redis服务启动了吗？
你好db:mysql 中的database怎么配置

**Comment by llfididi** [comment]
> > 你的本地mysql和redis服务启动了吗？
> > 你好db:mysql 中的database怎么配置

不太懂那个数据库什么的，我都没下载安装，还要学一下再跑这个项目

**Comment by llfididi** [comment]
> > 你的本地mysql和redis服务启动了吗？
> > 你好db:mysql 中的database怎么配置

你好，我配置完了，要安装mysql 和 redis，有问题可以联系我

![image.png](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/87f6eab0f0784320892888bd568df8ef~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=1352&h=730&s=71979&e=png&b=f8f8f8)


![image.png](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/8cb92345638944fe86826531e5d3e2b5~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=314&h=328&s=30196&e=png&b=1e1e1e)

**Comment by zhengwenhong123** [comment]
> > > 你的本地mysql和redis服务启动了吗？
> > > 你好db:mysql 中的database怎么配置
> 
> 你好，我配置完了，要安装mysql 和 redis，有问题可以联系我
> 
> ![image.png](https://camo.githubusercontent.com/3f7db753632eb53643a0e4d444703bd9254915b9a00fbffaa820987a3fe6c891/68747470733a2f2f70392d6a75656a696e2e62797465696d672e636f6d2f746f732d636e2d692d6b3375316662706663702f38376636656162306630373834333230383932383838626435363864663865667e74706c762d6b3375316662706663702d6a6a2d6d61726b3a303a303a303a303a7137352e696d616765233f773d3133353226683d37333026733d373139373926653d706e6726623d663866386638)
> 
> ![image.png](https://camo.githubusercontent.com/9d77b003b6f68828ca5f66d34d590318df5b9d01dd5878809f6c83957525354e/68747470733a2f2f70392d6a75656a696e2e62797465696d672e636f6d2f746f732d636e2d692d6b3375316662706663702f38636239323334353633383934346665383638323635333165356433653262357e74706c762d6b3375316662706663702d6a6a2d6d61726b3a303a303a303a303a7137352e696d616765233f773d33313426683d33323826733d333031393626653d706e6726623d316531653165)



> > 你的本地mysql和redis服务启动了吗？
> > 你好db:mysql 中的database怎么配置



> > > 你的本地mysql和redis服务启动了吗？
> > > 你好db:mysql 中的database怎么配置
> 
> 你好，我配置完了，要安装mysql 和 redis，有问题可以联系我
> 
> ![image.png](https://camo.githubusercontent.com/3f7db753632eb53643a0e4d444703bd9254915b9a00fbffaa820987a3fe6c891/68747470733a2f2f70392d6a75656a696e2e62797465696d672e636f6d2f746f732d636e2d692d6b3375316662706663702f38376636656162306630373834333230383932383838626435363864663865667e74706c762d6b3375316662706663702d6a6a2d6d61726b3a303a303a303a303a7137352e696d616765233f773d3133353226683d37333026733d373139373926653d706e6726623d663866386638)
> 
> ![image.png](https://camo.githubusercontent.com/9d77b003b6f68828ca5f66d34d590318df5b9d01dd5878809f6c83957525354e/68747470733a2f2f70392d6a75656a696e2e62797465696d672e636f6d2f746f732d636e2d692d6b3375316662706663702f38636239323334353633383934346665383638323635333165356433653262357e74706c762d6b3375316662706663702d6a6a2d6d61726b3a303a303a303a303a7137352e696d616765233f773d33313426683d33323826733d333031393626653d706e6726623d316531653165)

好的 谢谢 我的已经跑起来了

**Comment by zhengwenhong123** [comment]
> > > 你的本地mysql和redis服务启动了吗？
> > > 你好db:mysql 中的database怎么配置
> 
> 你好，我配置完了，要安装mysql 和 redis，有问题可以联系我
> 
> ![image.png](https://camo.githubusercontent.com/3f7db753632eb53643a0e4d444703bd9254915b9a00fbffaa820987a3fe6c891/68747470733a2f2f70392d6a75656a696e2e62797465696d672e636f6d2f746f732d636e2d692d6b3375316662706663702f38376636656162306630373834333230383932383838626435363864663865667e74706c762d6b3375316662706663702d6a6a2d6d61726b3a303a303a303a303a7137352e696d616765233f773d3133353226683d37333026733d373139373926653d706e6726623d663866386638)
> 
> ![image.png](https://camo.githubusercontent.com/9d77b003b6f68828ca5f66d34d590318df5b9d01dd5878809f6c83957525354e/68747470733a2f2f70392d6a75656a696e2e62797465696d672e636f6d2f746f732d636e2d692d6b3375316662706663702f38636239323334353633383934346665383638323635333165356433653262357e74706c762d6b3375316662706663702d6a6a2d6d61726b3a303a303a303a303a7137352e696d616765233f773d33313426683d33323826733d333031393626653d706e6726623d316531653165)

我是之前的数据表没有配置好 没有把sql文件导入进去 哈哈

**Comment by wuxiao-ling197** [comment]
你好，我yarn安装完server依赖后yarn start启动项目，但是报错：
![1](https://github.com/user-attachments/assets/43e2e855-3fbc-418e-a9ca-de3a6dc7f3c7)
应该要怎么解决这个问题呢

**Comment by taozhi1010** [comment]
yarn start 命令没有默认环境 使用yarn start:dev试试

**Comment by wuxiao-ling197** [comment]
> yarn start 命令没有默认环境 使用yarn start:dev试试

可以了！感谢！！
