### ISSUE TITLE
【参数设置模块】系统内置，这个字段的存在意义不明

### ISSUE THREAD

**Issue by CrazyStudent13** [taozhi1010/nest-admin#36]
【参数设置】模块的系统内置（config_type）字段意义不明，如果有必要，我个人这里开了个分支删除之后，确认没有什么影响。
是否可以在这之后移除该字段？
如果可以的话，我后续会将自己的分支提交到正式分支上。
![image](https://github.com/user-attachments/assets/a74b2637-9bea-4e00-abcc-eeb564f397db)

**Comment by CrazyStudent13** [comment]
关于这个模块，注册功能也可以移除掉，毕竟后台管理系统一般很少开放注册，这个配置没什么用。

**Comment by taozhi1010** [comment]
注册功能还是保留

**Comment by CrazyStudent13** [comment]
> 注册功能还是保留

好的，那我这边能删掉系统内置字段吗？（主要是在实际使用中感觉没什么用）

**Comment by taozhi1010** [comment]
这个字段有意义 在群里有解释过 
标识不可删除标记

**Comment by CrazyStudent13** [comment]
> 这个字段有意义 在群里有解释过 标识不可删除标记
好吧
