### ISSUE TITLE
nest-admin/admin 启动失败

### ISSUE THREAD

**Issue by Jsmond2016** [taozhi1010/nest-admin#4]
node 版本： 16.18.0
系统： windows 10

按照流程

```
# 建议不要直接使用 cnpm 安装依赖，会有各种诡异的 bug。可以通过如下操作解决 npm 下载速度慢的问题
npm install --registry=https://registry.npmmirror.com

# 启动服务
npm run dev
```

错误如图：

![image](https://github.com/taozhi1010/nest-admin/assets/25282180/105ba417-0268-4497-becb-d34ef133d142)

**Comment by llfididi** [comment]
> node 版本： 16.18.0 系统： windows 10
> 
> 按照流程
> 
> ```
> # 建议不要直接使用 cnpm 安装依赖，会有各种诡异的 bug。可以通过如下操作解决 npm 下载速度慢的问题
> npm install --registry=https://registry.npmmirror.com
> 
> # 启动服务
> npm run dev
> ```
> 
> 错误如图：
> 
> ![image](https://private-user-images.githubusercontent.com/25282180/329859876-105ba417-0268-4497-becb-d34ef133d142.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1Njc4NDYsIm5iZiI6MTcxNTU2NzU0NiwicGF0aCI6Ii8yNTI4MjE4MC8zMjk4NTk4NzYtMTA1YmE0MTctMDI2OC00NDk3LWJlY2ItZDM0ZWYxMzNkMTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAyMzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NjM0ZDIwYTFhYWU1NmQ5N2I3MGE3MDgzMTgzNGI2OTUxOWZiOGIxMDYxOTg2ZmRmMGFmMTAwMzc3ODJkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vXfsKMiVJQhJa10fdXOLTLjIQeLyyfE-tTs4FYjce3g)

安装 core-js

**Comment by wuxiao-ling197** [comment]
@Jsmond2016 你好 我运行启动admin的时候报错是 
```
 INFO  Starting development server...
95% emitting CompressionPlugin ERROR  Error: error:0308010C:digital envelope routines::unsupported
```
![1](https://github.com/user-attachments/assets/26bbb937-aa1a-4943-9f7b-d8dbf15b4b15)
是什么原因呢 ？有什么解决办法吗？
