### ISSUE TITLE
关于 create_by 和 update_by 问题

### ISSUE THREAD

**Issue by a876691666** [taozhi1010/nest-admin#42]
是否应该存int类型的id字段 而不是varchat的name。存在更改用户名的可能性，无法追溯。

**Comment by taozhi1010** [comment]
int类型的话 大数前后端都不好处理，看看有没有其它比较好的方式呢

**Comment by taozhi1010** [comment]
可以加我wx交流哦大佬 taozhi10100

**Comment by a876691666** [comment]
芋道那边数据库id都是用 bigint
